# Data

In [ ]:
q = 0.1
fname = "DATA/dataRBM_q"+str(q)+"_4state.csv"
# Visible data
v = np.loadtxt(fname,delimiter=",",dtype=int)
N = len(v)
# Length of sample
L = len(v[0])
print(f"Each of N={N} data samples has L={L} digits.")

# Data without corruption
q = 0
fname = "DATA/dataRBM_q"+str(q)+"_4state.csv"
# Visible data
v_true = np.loadtxt(fname,delimiter=",",dtype=int)

for n in range(10):
    print(v[n])

print("...")

# Choice of using -1/+1 and not 0,1
SPINS = False
if SPINS:
    vmin = -1
# The energy gap now is 2 not 1
    GAP  = 2  
    v = 2*v -1
else:
    vmin = 0
    GAP = 1

# Store initial values
v0 = np.zeros_like(v)
v0[:] = v[:]

for n in range(10):
    print(v[n])

print("...")

Each of N=10000 data samples has L=8 digits.
[1 1 0 0 1 1 0 0]
[1 1 0 0 0 1 1 0]
[0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 1]
[1 1 0 1 1 1 1 1]
[1 1 1 1 0 1 1 1]
[0 0 1 1 1 0 1 1]
[0 0 1 1 1 1 0 0]
[1 1 0 0 1 1 0 0]
[0 0 0 1 1 0 1 1]
...
[1 1 0 0 1 1 0 0]
[1 1 0 0 0 1 1 0]
[0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 1]
[1 1 0 1 1 1 1 1]
[1 1 1 1 0 1 1 1]
[0 0 1 1 1 0 1 1]
[0 0 1 1 1 1 0 0]
[1 1 0 0 1 1 0 0]
[0 0 0 1 1 0 1 1]
...


In [ ]:
# Number of hidden units
M = 5

# This is good, is written in the review the denom is prop to the lenght of M
sigma = np.sqrt(4. /float(L + M))
np.random.seed(12345)

# Numbers in [-sigma;sigma]
w = sigma * (2*np.random.rand(L,M) - 1) #matrix of weights
a = sigma * (2*np.random.rand(L) - 1)
b = np.zeros(M)
print(f"w = {w}\na = {a}\nb = {b}")
w0,a0,b0 = np.zeros_like(w),np.zeros_like(a),np.zeros_like(b)
w0[:],a0[:],b0[:] = w[:],a[:],b[:]

NameError: name 'np' is not defined

In [ ]:
w1,a1,b1 = RBM(w, v, a, b, plot = False)

In [ ]:
pixi = 1
print("------------ β=1 ------------ ")
v1 = np.full((N,L),vmin)
for n in range(N):
    h = activate(v0[n],w1,b1,GAP,β=1)
    v1[n] = activate(h,w1.T,a1,GAP,β=1)
    
for n in range(10):
    print((v0[n]).astype(int),(v1[n]).astype(int))

print(f"The score of the RBM with β = 1 and a confidence of {pixi} is {comparison(v1,v_true,pixi)} ")
print("------------ β=5 ------------ ")
v2 = np.full((N,L),vmin)
for n in range(N):
    h = activate(v0[n],w1,b1,GAP,β=5)
    v2[n] = activate(h,w1.T,a1,GAP, β=5)
    
for n in range(10):
    print((v0[n]).astype(int),(v2[n]).astype(int))    

print(f"The score of the RBM with β = 5 and a confidence of {pixi} is {comparison(v2,v_true,pixi)} ")

print("----------- β=10 ----------- ")
v3 = np.full((N,L),vmin)
for n in range(N):
    h = activate(v0[n],w1,b1,GAP,β=10)
    v3[n] = activate(h,w1.T,a1,GAP,β=10)
    
for n in range(10):
    print((v0[n]).astype(int),(v3[n]).astype(int))

print(f"The score of the RBM with β = 10 and a confidence of {pixi} is {comparison(v3,v_true,pixi)} ")
    
print("----------- β=15 ----------- ")
v4 = np.full((N,L),vmin)
for n in range(N):
    h = activate(v0[n],w1,b1,GAP,β=15)
    v4[n] = activate(h,w1.T,a1,GAP,β=15)
    
for n in range(10):
    print((v0[n]).astype(int),(v4[n]).astype(int))

print(f"The score of the RBM with β = 15 and a confidence of {pixi} is {comparison(v4,v_true,pixi)} ")

------------ β=1 ------------ 
[1 1 0 0 1 1 0 0] [1 1 0 1 1 1 0 0]
[1 1 0 0 0 1 1 0] [1 1 0 0 1 0 1 0]
[0 1 0 1 1 1 0 0] [0 1 0 1 1 1 0 1]
[0 0 1 1 0 0 1 1] [0 0 1 1 0 0 1 1]
[1 1 0 1 1 1 1 1] [1 1 1 1 1 1 1 1]
[1 1 1 1 0 1 1 1] [1 1 1 1 0 0 1 1]
[0 0 1 1 1 0 1 1] [0 0 1 1 1 0 0 0]
[0 0 1 1 1 1 0 0] [0 0 1 1 1 1 0 0]
[1 1 0 0 1 1 0 0] [1 1 0 0 1 1 0 0]
[0 0 0 1 1 0 1 1] [0 0 1 1 0 0 1 1]
10000
8
The score of the RBM with β = 1 and a confidence of 2 is 0.6706 
------------ β=5 ------------ 
[1 1 0 0 1 1 0 0] [1 1 0 0 1 1 0 0]
[1 1 0 0 0 1 1 0] [1 1 0 0 1 1 0 0]
[0 1 0 1 1 1 0 0] [1 1 0 0 1 1 0 0]
[0 0 1 1 0 0 1 1] [0 0 1 1 0 0 1 1]
[1 1 0 1 1 1 1 1] [1 1 1 1 1 1 1 1]
[1 1 1 1 0 1 1 1] [1 1 1 1 1 1 1 1]
[0 0 1 1 1 0 1 1] [1 1 1 1 0 1 1 1]
[0 0 1 1 1 1 0 0] [0 0 1 1 1 1 0 0]
[1 1 0 0 1 1 0 0] [1 1 0 0 1 1 0 0]
[0 0 0 1 1 0 1 1] [1 1 1 1 0 0 1 1]
10000
8
The score of the RBM with β = 5 and a confidence of 2 is 0.877 
----------- β=10 ----------- 
[1 1 0 0 1 1 0 0] [1 1 0 0 1 1 0 0]
[1 1 0 

In [ ]:
M = [3,5,7,10]
score_m = []

for m in M:
    w = sigma * (2*np.random.rand(L,M) - 1) #matrix of weights
    a = sigma * (2*np.random.rand(L) - 1)
    b = np.zeros(M)
    print(f"w = {w}\na = {a}\nb = {b}")
    w0,a0,b0 = np.zeros_like(w),np.zeros_like(a),np.zeros_like(b)
    w0[:],a0[:],b0[:] = w[:],a[:],b[:]

    w1,a1,b1 = RBM(w, v, a, b, plot = False)

    for n in range(N):
        h = activate(v0[n],w1,b1,GAP,β=3)
        v1[n] = activate(h,w1.T,a1,GAP,β=3)
    score_m.append(comparison(v1, v_true, pixi))

NameError: name 'sigma' is not defined

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=dc341315-a668-4e89-92e9-cab634ea884a' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>